/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mizan.view;

import com.mizan.connection.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mohdm
 */
public class CountingDataDelete extends javax.swing.JFrame {

    /**
     * Creates new form DataDelete
     */
    public CountingDataDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jBack = new javax.swing.JButton();
        jAllData = new javax.swing.JButton();
        jIndividualData = new javax.swing.JButton();
        jSearch = new javax.swing.JButton();
        jVoterName = new javax.swing.JLabel();
        jtxt_search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Counting's Data Delete");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 540, 50));

        jPanel7.setBackground(new java.awt.Color(0, 102, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 32));

        jBack.setIcon(new javax.swing.ImageIcon("G:\\IT Files\\Pratices Files\\All Swing\\vote_management\\src\\com\\mizan\\pic\\back.png")); // NOI18N
        jBack.setBorder(null);
        jBack.setContentAreaFilled(false);
        jBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackActionPerformed(evt);
            }
        });
        jPanel7.add(jBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jAllData.setBackground(new java.awt.Color(204, 0, 0));
        jAllData.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jAllData.setText("All Data");
        jAllData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jAllData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAllDataActionPerformed(evt);
            }
        });
        jPanel7.add(jAllData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, 50));

        jPanel5.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 580));

        jIndividualData.setBackground(new java.awt.Color(204, 0, 0));
        jIndividualData.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jIndividualData.setText("Individual Data");
        jIndividualData.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jIndividualData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIndividualDataActionPerformed(evt);
            }
        });
        jPanel5.add(jIndividualData, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 200, 50));

        jSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSearch.setForeground(new java.awt.Color(0, 102, 0));
        jSearch.setText("Search");
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchActionPerformed(evt);
            }
        });
        jPanel5.add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 220, 110, 50));

        jVoterName.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jVoterName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jVoterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 260, 30));

        jtxt_search.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jPanel5.add(jtxt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(571, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  static Connection connect = DBConnection.getConnection();
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //        new adminlogin().setVisible(true);
        //        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackActionPerformed
        // TODO add your handling code here:
        new DataDelete().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBackActionPerformed

    private void jAllDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAllDataActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure delete ALL DATA!", "WORNING", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "delete from result";
                PreparedStatement ps = connect.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "All Data are deleted");
            } catch (SQLException ex) {
            }
        }
    }//GEN-LAST:event_jAllDataActionPerformed

    private void jIndividualDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIndividualDataActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure delete ALL DATA!", "WORNING", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            try {
                String sql = "delete from result where id=?";
                PreparedStatement ps = connect.prepareStatement(sql);
                ps.setString(1, jtxt_search.getText());
                ps.execute();
                JOptionPane.showMessageDialog(null, "Selected data is deleted");
            } catch (SQLException ex) {

            }
        }
        jtxt_search.setText(null);
        jVoterName.setText(null);
    }//GEN-LAST:event_jIndividualDataActionPerformed

    private void jSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchActionPerformed
        if (!jtxt_search.getText().equals("")) {
            String str = jtxt_search.getText();
            try {
                String url = "select * from result where id=?";
                PreparedStatement ps = connect.prepareStatement(url);
                ps.setString(1, str);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    String s = rs.getString(2);
                    jVoterName.setText(s);
                }
            } catch (SQLException ex) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "ID not selected!");
        }
    }//GEN-LAST:event_jSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CountingDataDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CountingDataDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CountingDataDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CountingDataDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CountingDataDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAllData;
    private javax.swing.JButton jBack;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jIndividualData;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jSearch;
    private javax.swing.JLabel jVoterName;
    private javax.swing.JTextField jtxt_search;
    // End of variables declaration//GEN-END:variables
}
