package com.mizan.view;

import com.mizan.connection.DBConnection;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class UpdateCandidate extends javax.swing.JFrame {

    String filename = null;
    byte[] candidate_image = null;

    public UpdateCandidate() {
        initComponents();
        partysign();
    }

    public void partysign() {
        jPartysign.addItem("Dhaner Shish");
        jPartysign.addItem("Nouka");
        jPartysign.addItem("Langol");
        jPartysign.addItem("Mosal");
        jPartysign.addItem("Daripalla");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSex = new javax.swing.JTextField();
        jLeader = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jHeadQ = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jAge = new javax.swing.JTextField();
        jPartyName = new javax.swing.JTextField();
        jPartysign = new java.awt.Choice();
        jLabel17 = new javax.swing.JLabel();
        jCandidateId = new javax.swing.JTextField();
        jSearch = new javax.swing.JButton();
        jImage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jClear = new javax.swing.JButton();
        jCanUpdate = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Voter");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(155, 89, 182));
        jPanel2.setForeground(new java.awt.Color(125, 60, 152));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 32));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Candidate");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 60));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Update  ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 60));

        jButton2.setIcon(new javax.swing.ImageIcon("G:\\IT Files\\Pratices Files\\All Swing\\vote_management\\src\\com\\mizan\\pic\\back.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jSex.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 230, 30));

        jLeader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jLeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 230, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Party Leader");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 150, 20));

        jHeadQ.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jHeadQ.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jHeadQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 230, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Party Headquater");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 150, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Image");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 150, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Age");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 150, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Name Of Party");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 150, 20));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Party Sign");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 150, 20));

        jAge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 230, 30));

        jPartyName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPartyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jPartyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 30));

        jPartysign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel1.add(jPartysign, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 230, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Candidate ID");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 150, 20));

        jCandidateId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCandidateId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel1.add(jCandidateId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, 30));

        jSearch.setBackground(new java.awt.Color(204, 153, 0));
        jSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jSearch.setForeground(new java.awt.Color(0, 0, 153));
        jSearch.setText("Search");
        jSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        jSearch.setContentAreaFilled(false);
        jSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSeachActionPerformed(evt);
            }
        });
        jPanel1.add(jSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 90, 30));

        jImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 190));

        jPanel8.setBackground(new java.awt.Color(155, 89, 182));
        jPanel8.setLayout(null);

        jClear.setBackground(new java.awt.Color(255, 255, 255));
        jClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jClear.setForeground(new java.awt.Color(255, 255, 255));
        jClear.setIcon(new javax.swing.ImageIcon("G:\\IT Files\\Pratices Files\\All Swing\\vote_management\\src\\com\\mizan\\pic\\clear1.png")); // NOI18N
        jClear.setBorder(null);
        jClear.setContentAreaFilled(false);
        jClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClearActionPerformed(evt);
            }
        });
        jPanel8.add(jClear);
        jClear.setBounds(470, 0, 50, 60);

        jCanUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jCanUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jCanUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jCanUpdate.setIcon(new javax.swing.ImageIcon("G:\\IT Files\\Pratices Files\\All Swing\\vote_management\\src\\com\\mizan\\pic\\save.png")); // NOI18N
        jCanUpdate.setBorder(null);
        jCanUpdate.setContentAreaFilled(false);
        jCanUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCanUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCanUpdateActionPerformed(evt);
            }
        });
        jPanel8.add(jCanUpdate);
        jCanUpdate.setBounds(290, 0, 50, 61);

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 580, 70));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Sex");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(570, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
static Connection connect = DBConnection.getConnection();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Home home = new Home();
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    String imgPath = null;

    public ImageIcon ResizeImage(String ImagePath, byte[] pic) {
        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(jImage.getWidth(), jImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;

    }
    private void jCanUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCanUpdateActionPerformed
        try {
//            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/vote_management", "root", "12345");
            String sql = "update addcandidate set partyname='" + jPartyName.getText() + "',partyleader='" + jLeader.getText() + "',sex='" + jSex.getText() + "',age='" + jAge.getText() + "',partyHQ='" + jHeadQ.getText() + "',partysign='" + jPartysign.getItem(jPartysign.getSelectedIndex()) + "' where candidateid='" + jCandidateId.getText() + "'";
            Statement ps = connect.createStatement();
            ps.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data Updated Successfully");
            Home home = new Home();
            home.setVisible(true);
            dispose();

        } catch (SQLException ex) {
            Logger.getLogger(UpdateCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jCanUpdateActionPerformed

    private void jClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClearActionPerformed
        jCandidateId.setText(null);
        jPartyName.setText(null);
        jLeader.setText(null);
        jSex.setText(null);
        jAge.setText(null);
        jHeadQ.setText(null);
        jImage.setIcon(null);
//        jPartysign.();
    }//GEN-LAST:event_jClearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jSeachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSeachActionPerformed
        try {
            String str = jCandidateId.getText();
//            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/vote_management", "root", "12345");
            PreparedStatement ps = connect.prepareStatement("select * from addcandidate where candidateid=?");
            ps.setString(1, str);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String s = rs.getString(2);
                jPartyName.setText(s);
                String s1 = rs.getString(3);
                jLeader.setText(s1);
                String s2 = rs.getString(4);
                jSex.setText(s2);
                String s3 = rs.getString(5);
                jAge.setText(s3);
                String s4 = rs.getString(6);
                jHeadQ.setText(s4);
                byte[] s5 = rs.getBytes(8);

                ImageIcon imageicon = new ImageIcon(new ImageIcon(s5).getImage().getScaledInstance(jImage.getWidth(), jImage.getHeight(), Image.SCALE_SMOOTH));
                jImage.setIcon(imageicon);

            } else {
                JOptionPane.showMessageDialog(null, "Candidate Id not Found");
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateCandidate.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jSeachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCandidate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCandidate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCanUpdate;
    private javax.swing.JTextField jCandidateId;
    private javax.swing.JButton jClear;
    private javax.swing.JTextField jHeadQ;
    private javax.swing.JLabel jImage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jLeader;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jPartyName;
    private java.awt.Choice jPartysign;
    private javax.swing.JButton jSearch;
    private javax.swing.JTextField jSex;
    // End of variables declaration//GEN-END:variables
}
