/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CandidateForm;
import Initiate.Index;
/**
 *
 * @author Mystery 92
 */
public class ResultsForm extends javax.swing.JFrame {
int i=1;
    /**
     * Creates new form ResultsForm
     */
    public ResultsForm() {
        initComponents();
    }
    
    public ResultsForm(String constituency){
        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new javax.swing.ImageIcon("C:\\Users\\Mystery 92\\Documents\\NetBeansProjects\\Voter Form\\src\\user.png").getImage());
        jlconst.setText(constituency);
        CandidateManager cm=new CandidateManager();
        Candidates candidates=new Candidates();
        candidates=cm.viewResult(constituency);
        jlcandirecord.setText(""+i/*Integer.toString(candidates.getCandidateID())*/);
        //i++;
        jtcandidatename.setText(candidates.getCandidateName());
        jtparty.setText(candidates.getParty());
        jtvotes.setText(Integer.toString(candidates.getVotes()));
                
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlconst = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtcandidatename = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtvotes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jlcandirecord = new javax.swing.JLabel();
        jbnextrecord = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbpreviousrecord = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtparty = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Constituency");

        jlconst.setToolTipText("Shows Constituency");

        jLabel2.setText("Candidate Name");

        jtcandidatename.setToolTipText("Dislays Candidate Name");

        jLabel3.setText("Votes");

        jtvotes.setToolTipText("Displays Number of Votes");
        jtvotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtvotesActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.setToolTipText("Takes Back to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbnextrecord.setText(">");
        jbnextrecord.setToolTipText("Shows Next Record");
        jbnextrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnextrecordActionPerformed(evt);
            }
        });

        jButton3.setText(">>");
        jButton3.setToolTipText("Shows Last Record");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbpreviousrecord.setText("<");
        jbpreviousrecord.setToolTipText("Shows Previous Record");
        jbpreviousrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpreviousrecordActionPerformed(evt);
            }
        });

        jButton5.setText("<<");
        jButton5.setToolTipText("Shows First Record");

        jLabel4.setText("Party");

        jtparty.setToolTipText("Displays Party Name");
        jtparty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpartyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jbpreviousrecord)
                        .addGap(18, 18, 18)
                        .addComponent(jlcandirecord, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jbnextrecord)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlconst, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtcandidatename, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jtvotes)
                    .addComponent(jtparty))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlconst, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtcandidatename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtparty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtvotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbnextrecord)
                        .addComponent(jButton3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbpreviousrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jlcandirecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtvotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtvotesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtvotesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbnextrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnextrecordActionPerformed
        // TODO add your handling code here:
        Candidates candidates=new Candidates();
        CandidateManager cm=new CandidateManager();
        candidates=cm.nextVal(i/*Integer.parseInt(jlcandrecord.getText())*/,jlconst.getText());
        i++;
        jlcandirecord.setText(""+i/*Integer.toString(candidates.getCandidateID())*/);
        jtcandidatename.setText(candidates.getCandidateName());
        jtparty.setText(candidates.getParty());
        jtvotes.setText(Integer.toString(candidates.getVotes()));
    }//GEN-LAST:event_jbnextrecordActionPerformed

    private void jbpreviousrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpreviousrecordActionPerformed
        // TODO add your handling code here:
        Candidates candidates=new Candidates();
        CandidateManager cm=new CandidateManager();
        candidates=cm.prevVal(i/*Integer.parseInt(jlcandrecord.getText())*/,jlconst.getText());
        i--;
        jlcandirecord.setText(""+i/*Integer.toString(candidates.getCandidateID())*/);
        jtcandidatename.setText(candidates.getCandidateName());
        jtparty.setText(candidates.getParty());
        jtvotes.setText(Integer.toString(candidates.getVotes()));
    }//GEN-LAST:event_jbpreviousrecordActionPerformed

    private void jtpartyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpartyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtpartyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ResultsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbnextrecord;
    private javax.swing.JButton jbpreviousrecord;
    public javax.swing.JLabel jlcandirecord;
    public javax.swing.JLabel jlconst;
    private javax.swing.JTextField jtcandidatename;
    private javax.swing.JTextField jtparty;
    private javax.swing.JTextField jtvotes;
    // End of variables declaration//GEN-END:variables
}
