package Initiate;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import CandidateForm.CandidateForm;
import ClerkForm.VoterForm;
import VoterForm.CandidateGUI;
/**
 *
 * @author Mystery 92
 */
public class Index extends javax.swing.JFrame {
String control;
    /**
     * Creates new form Menu
     */
    public Index() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon("C:\\Users\\Mystery 92\\Documents\\NetBeansProjects\\Voter Form\\src\\user.png").getImage());
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbClerk = new javax.swing.JButton();
        jbVoter = new javax.swing.JButton();
        jbCandidate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Voting System");

        jbClerk.setText("Clerk");
        jbClerk.setOpaque(false);
        jbClerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClerkActionPerformed(evt);
            }
        });

        jbVoter.setText("Voter");
        jbVoter.setOpaque(false);
        jbVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoterActionPerformed(evt);
            }
        });

        jbCandidate.setText("Candidate");
        jbCandidate.setOpaque(false);
        jbCandidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCandidateActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mystery 92\\Documents\\NetBeansProjects\\Voter Form\\src\\NewMenu.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jbClerk)
                .addGap(18, 18, 18)
                .addComponent(jbVoter)
                .addGap(18, 18, 18)
                .addComponent(jbCandidate)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCandidate)
                    .addComponent(jbVoter)
                    .addComponent(jbClerk))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbClerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClerkActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        VoterForm vf=new VoterForm();
        vf.setVisible(true);
    }//GEN-LAST:event_jbClerkActionPerformed

    private void jbCandidateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCandidateActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CandidateForm().setVisible(true);
    }//GEN-LAST:event_jbCandidateActionPerformed

    private void jbVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoterActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CandidateGUI().setVisible(true);
    }//GEN-LAST:event_jbVoterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbCandidate;
    private javax.swing.JButton jbClerk;
    private javax.swing.JButton jbVoter;
    // End of variables declaration//GEN-END:variables
}
