package ClerkForm;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mystery 92
 */

import Initiate.Index;
import ClerkForm.VoterFormManager;
import ExceptionHandling.InfoDialog;
import java.awt.image.BufferedImage;
import java.sql.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
public class VoterForm extends javax.swing.JFrame {
    /**
     * x and picfile are global variables
     * x is used to tell the program which of the CRUD operations to perform
     * picfile is used to contain image file for inserting and updating image file
     */
String x;       
File picfile;
boolean done;
    /**
     * Creates new form VoterForm
     */
    public VoterForm() {

        initComponents();
        setLocationRelativeTo(null);
        this.setIconImage(new javax.swing.ImageIcon("C:\\Users\\Mystery 92\\Documents\\NetBeansProjects\\Voter Form\\src\\user.png").getImage());
        /**
         * First Record displayed at the execution
         */
        VoterFormManager vot=new VoterFormManager();
        Voter v;
        v=vot.startup();
        
        jtfullname.setText(v.getVoter_fullname());
        jtcnic.setText(Long.toString(v.getVoter_cnic()));
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        /**
         * Picture displayed at the time of execution
         * this is part of the first record shown
         */
       try{
        javax.swing.ImageIcon im=new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
        jlpicture.setIcon(im);
        jlrecordno.setText("1");
       }catch(SQLException ex){System.out.println(ex);}
        
        /**
         * Populating the JComboBox from Database at startup
         */
        VoterFormManager voter=new VoterFormManager();
        VoterFormManager voter1=new VoterFormManager();
        Voter v2=new Voter();
        v2=voter.lastRecord();
        int j=v2.getVoter_id();
        Voter [] v1=new Voter[j];

            v1=voter1.searchfunc(j);
            
            for(int i=0;i<j;i++){
               
                jcsearch.addItem(/*v1[i].getVoter_id()+". "+*/v1[i].getVoter_fullname());
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlfullname = new javax.swing.JLabel();
        jlfathername = new javax.swing.JLabel();
        jlmobileno = new javax.swing.JLabel();
        jlphoneno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlpicture = new javax.swing.JLabel();
        jlemail = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jtfullname = new javax.swing.JTextField();
        jtmobileno = new javax.swing.JTextField();
        jtfathername = new javax.swing.JTextField();
        jtphoneno = new javax.swing.JTextField();
        jtemail = new javax.swing.JTextField();
        jbtakefirst = new javax.swing.JButton();
        jbpreviousval = new javax.swing.JButton();
        jbnextval = new javax.swing.JButton();
        jbtakelast = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jlrecordno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtcnic = new javax.swing.JTextField();
        jcsearch = new javax.swing.JComboBox();
        jbcreate = new javax.swing.JButton();
        jbsearch = new javax.swing.JButton();
        jbupdate = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        Ok = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Election Voting System");
        setBackground(new java.awt.Color(102, 255, 51));
        setFont(new java.awt.Font("Lucida Handwriting", 1, 10)); // NOI18N
        setResizable(false);

        jlfullname.setText("Full Name");

        jlfathername.setText("Father Name");

        jlmobileno.setText("Mobile No.");

        jlphoneno.setText("Phone No.");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        //jlpicture.addMouseListener(new MouseEvent evt);
        jlpicture.setBackground(new java.awt.Color(255, 255, 255));
        jlpicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlpictureMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlpicture, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        jlemail.setText("Email");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jtfullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfullnameActionPerformed(evt);
            }
        });

        jtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtemailActionPerformed(evt);
            }
        });

        jbtakefirst.setMnemonic('f');
        jbtakefirst.setText("<<");
        jbtakefirst.setToolTipText("Show First Record");
        jbtakefirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtakefirstActionPerformed(evt);
            }
        });

        jbpreviousval.setMnemonic('p');
        jbpreviousval.setText("<");
        jbpreviousval.setToolTipText("Show Previous Record");
        jbpreviousval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpreviousvalActionPerformed(evt);
            }
        });

        jbnextval.setMnemonic('n');
        jbnextval.setText(">");
        jbnextval.setToolTipText("Show Next Record");
        jbnextval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnextvalActionPerformed(evt);
            }
        });

        jbtakelast.setMnemonic('l');
        jbtakelast.setText(">>");
        jbtakelast.setToolTipText("Show Last Record");
        jbtakelast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtakelastActionPerformed(evt);
            }
        });

        jbdelete.setMnemonic('d');
        jbdelete.setText("Delete");
        jbdelete.setToolTipText("Delete a Voter Record");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        jLabel2.setText("CNIC");

        jtcnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcnicActionPerformed(evt);
            }
        });

        jcsearch.setToolTipText("Shows List of Full Name contained in the Database");
        jcsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcsearchActionPerformed(evt);
            }
        });

        jbcreate.setMnemonic('c');
        jbcreate.setText("Create");
        jbcreate.setToolTipText("Enter Voter Detail into Database");
        jbcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcreateActionPerformed(evt);
            }
        });

        jbsearch.setMnemonic('s');
        jbsearch.setText("Search");
        jbsearch.setToolTipText("Searching is done using Full Name and CNIC");
        jbsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsearchActionPerformed(evt);
            }
        });

        jbupdate.setMnemonic('u');
        jbupdate.setText("Update");
        jbupdate.setToolTipText("Update current information");
        jbupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbupdateActionPerformed(evt);
            }
        });

        Cancel.setMnemonic('r');
        Cancel.setText("Cancel");
        Cancel.setToolTipText("Cancel Refreshes all Fields");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Ok.setMnemonic('o');
        Ok.setText("Ok");
        Ok.setToolTipText("After Selecting Click on Ok to perform Function");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.setToolTipText("Takes Back to Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcsearch, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jlfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfathername, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtcnic, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jlmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlemail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbcreate, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jbsearch)
                        .addGap(18, 18, 18)
                        .addComponent(jbupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jbdelete)
                        .addGap(49, 49, 49)
                        .addComponent(jbtakefirst))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cancel)
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jbpreviousval, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlrecordno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbnextval)
                .addGap(18, 18, 18)
                .addComponent(jbtakelast)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlfullname)
                            .addComponent(jlfathername)
                            .addComponent(jtfathername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtcnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlmobileno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlphoneno)
                                    .addComponent(jtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlemail)
                                    .addComponent(jtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jbcreate)
                                    .addComponent(jbsearch)
                                    .addComponent(jbupdate)
                                    .addComponent(jbdelete))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jlrecordno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jbtakefirst)
                                        .addComponent(jbtakelast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbpreviousval)
                                        .addComponent(jbnextval, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(Ok)
                    .addComponent(jButton1))
                .addGap(104, 104, 104)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Event handling for Create(jbcreate) Button
     * @param evt 
     * jtfullname is JTextField which takes Full Name of Voter
     * jtcnic is JTextField which takes CNIC of Voter
     * jtfathername is JTextField which takes Father Name of Voter
     * jtphoneno is JTextField which takes Phone Number of Voter
     * jtmobileno is JTextField which takes Mobile Number of Voter
     * jtemail is JTextField which takes Email of Voter
     */
    private void jbcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcreateActionPerformed
        //TODO add your handling code here:
        jtfullname.setText("");
        jtcnic.setText("");
        jtfathername.setText("");
        jtphoneno.setText("");
        jtmobileno.setText("");
        jtemail.setText("");
        javax.swing.ImageIcon im=new javax.swing.ImageIcon("C:\\Users\\Mystery 92\\Documents\\NetBeansProjects\\SE Project\\src\\Images\\user.png");
        jlpicture.setIcon(im);
        x="Create";
    }//GEN-LAST:event_jbcreateActionPerformed
    /**
     * Event handling for Search(jbsearch) Button
     * @param evt 
     */
    private void jbsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsearchActionPerformed
        // TODO add your handling code here:
        jtfullname.setText("");
        jtcnic.setText("");
        jtfathername.setText("");
        jtphoneno.setText("");
        jtmobileno.setText("");
        jtemail.setText("");
        x="Search";
    }//GEN-LAST:event_jbsearchActionPerformed
    /**
     * Event handling for Update(jbupdate) Button
     * @param evt 
     */
    private void jbupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbupdateActionPerformed
        // TODO add your handling code here:
      /*  jtfullname.setText("");
        jtcnic.setText("");
        jtfathername.setText("");
        jtphoneno.setText("");
        jtmobileno.setText("");
        jtemail.setText("");*/
        x="Update";
    }//GEN-LAST:event_jbupdateActionPerformed
    /**
     * Event handling for Delete(jbdelete) Button
     * @param evt 
     */
    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
       /* jtfullname.setText("");
        jtcnic.setText("");
        jtfathername.setText("");
        jtphoneno.setText("");
        jtmobileno.setText("");
        jtemail.setText("");*/
        x="Delete";
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jtfullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfullnameActionPerformed
     /**
     * Event handling for >>(last record)(jbtakelast) Button
     * @param evt 
     */
    private void jbtakelastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtakelastActionPerformed
        // TODO add your handling code here:
        VoterFormManager vot=new VoterFormManager();
        Voter v=new Voter();
        int i=Integer.parseInt(jlrecordno.getText());
        v=vot.lastRecord();
        jtfullname.setText(v.getVoter_fullname());      
        jtcnic.setText(Long.toString(v.getVoter_cnic()));   
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        jlrecordno.setText(Integer.toString(v.getVoter_id()));
        try{
            javax.swing.ImageIcon im=new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
            jlpicture.setIcon(im);
        }catch(SQLException ex){System.out.println(ex);}
    }//GEN-LAST:event_jbtakelastActionPerformed
    /**
     * Event handling behind the OK (Ok) Button
     * @param evt 
     */
    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        // TODO add your handling code here:
        //Create Function
        javax.swing.ImageIcon imageIcon;
        if(x.equals("Create")){
            System.out.println("Done");
         if(jtfullname.getText().equals("") || jtcnic.getText().equals("") || jtfathername.getText().equals("") || jtphoneno.getText().equals("") || jtmobileno.getText().equals("") || jtemail.getText().equals("")){
                new InfoDialog("Empty Fields",1).setVisible(true);
            }
        else{
                VoterFormManager vot=new VoterFormManager();
                Voter v=new Voter();
                v.setVoter_fullname(jtfullname.getText());
                v.setVoter_fathername(jtfathername.getText());
                String fullname=jtfullname.getText();
                String fathername=jtfathername.getText();
                int cnic=Integer.parseInt(jtcnic.getText());
                String email=jtemail.getText();
                int phone=Integer.parseInt(jtphoneno.getText());
                int mobile=Integer.parseInt(jtmobileno.getText());
                //File f=new File("user.png");
                done=vot.insertVoter(fullname,cnic,fathername,phone,mobile,email,picfile);
                if(done==true){
                    new InfoDialog("Voter Details Entered",2).setVisible(true);
                }
                else{
                    new InfoDialog("Voter Details Not Entered",2).setVisible(true);
                }
            }
        }
        //Search Function
        if(x.equals("Search")){
                VoterFormManager vot=new VoterFormManager();
                Voter v=new Voter();
                String fullname=jtfullname.getText();
                int cnic=Integer.parseInt(jtcnic.getText());
                try{
                    v=vot.searchVoter(fullname,cnic);
                    jlrecordno.setText(Integer.toString(v.getVoter_id()));
                    jtfullname.setText(v.getVoter_fullname());
                    jtfathername.setText(v.getVoter_fathername());
                    jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
                    jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
                    jtemail.setText(v.getVoter_email());
                    imageIcon = new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
                    jlpicture.setIcon(imageIcon);
                }catch(SQLException exc){System.out.println(exc);}
            }
        //Update Function
        if(x.equals("Update")){
            VoterFormManager vot=new VoterFormManager();
            Voter v=new Voter();
            String fullname=jtfullname.getText();
            int cnic=Integer.parseInt(jtcnic.getText());
            String fathername=jtfathername.getText();
            int phone=Integer.parseInt(jtphoneno.getText());
            int mobile=Integer.parseInt(jtmobileno.getText());
            String email=jtemail.getText();
            done=vot.updateVoter(fullname,cnic,fathername,phone,mobile,email,picfile);
            if(done==true){
                new InfoDialog("Voter Details Updated",2).setVisible(true);
            }
            else{
                new InfoDialog("Voter Details Not Updated",2).setVisible(true);
            }
        }
        //Delete Function
        if(x.equals("Delete")){
            VoterFormManager vot=new VoterFormManager();
            Voter v=new Voter();
            String fullname=jtfullname.getText();
            int cnic=Integer.parseInt(jtcnic.getText());
            done=vot.deleteVoter(fullname,cnic);
            if(done==true){
                    new InfoDialog("Voter Details Deleted",2).setVisible(true);
            }
            else{
                    new InfoDialog("Voter Details Not Deleted",2).setVisible(true);
            }
        }
    }//GEN-LAST:event_OkActionPerformed
    /**
     * Event handling behind Cancel (Cancel) Button
     * @param evt 
     */
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        jtfullname.setText("");
        jtcnic.setText("");
        jtfathername.setText("");
        jtphoneno.setText("");
        jtmobileno.setText("");
        jtemail.setText("");
        x="";
    }//GEN-LAST:event_CancelActionPerformed

    private void jtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtemailActionPerformed

    private void jtcnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcnicActionPerformed
    /**
     * Event handling behind > (jbnext) Button, shows the next record in the database
     * @param evt 
     */
    private void jbnextvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnextvalActionPerformed
        // TODO add your handling code here:
        VoterFormManager vot=new VoterFormManager();
        Voter v=new Voter();
        javax.swing.ImageIcon imageIcon;
        int i=Integer.parseInt(jlrecordno.getText());
        v=vot.nextVal(i);
        jtfullname.setText(v.getVoter_fullname());
        jtcnic.setText(Long.toString(v.getVoter_cnic()));
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        try{
        imageIcon = new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
        jlpicture.setIcon(imageIcon);
        }catch(SQLException ex){System.out.println(ex);}
        i++;
        //jlrecordno.setText(""+(i));
        jlrecordno.setText(Integer.toString(v.getVoter_id()));
    }//GEN-LAST:event_jbnextvalActionPerformed
    /**
     * Event handling behind < (jbprevious) Button, shows the previous record in the database
     * @param evt 
     */
    private void jbpreviousvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpreviousvalActionPerformed
        // TODO add your handling code here:
        VoterFormManager vot=new VoterFormManager();
        Voter v=new Voter();
        javax.swing.ImageIcon imageIcon;
        int i=Integer.parseInt(jlrecordno.getText());
        v=vot.prevVal(i);
        jtfullname.setText(v.getVoter_fullname());
        jtcnic.setText(Long.toString(v.getVoter_cnic()));
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        try{
        imageIcon = new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
        jlpicture.setIcon(imageIcon);
        }catch(SQLException ex){System.out.println(ex);}
        i--;
        //jlrecordno.setText(""+(i));
        jlrecordno.setText(Integer.toString(v.getVoter_id()));
    }//GEN-LAST:event_jbpreviousvalActionPerformed
    /**
     * Event handling behind <<(jbtakefirst) Button, shows the First record in the database
     * @param evt 
     */
    private void jbtakefirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtakefirstActionPerformed
        // TODO add your handling code here:
        VoterFormManager vot=new VoterFormManager();
        Voter v=new Voter();
        int i=Integer.parseInt(jlrecordno.getText());
        v=vot.firstRecord();
        jtfullname.setText(v.getVoter_fullname());
        jtcnic.setText(Long.toString(v.getVoter_cnic()));
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        jlrecordno.setText(Integer.toString(v.getVoter_id()));
        javax.swing.ImageIcon im;
    try {
        im = new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
        jlpicture.setIcon(im);
    } catch (SQLException ex) {
        Logger.getLogger(VoterForm.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jbtakefirstActionPerformed
    /**
     * Event handling behind JComboBox (jcsearch) Button, shows the records in the database
     * @param evt 
     */
    private void jcsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcsearchActionPerformed
    try {
        // TODO add your handling code here:
        //System.out.println(jcsearch.getItemCount());
        //System.out.println(jcsearch.getItemAt(0));
        //System.out.println("Index "+jcsearch.getSelectedIndex());
        String s=(String) jcsearch.getSelectedItem();
        javax.swing.ImageIcon imageIcon;
        VoterFormManager vot= new VoterFormManager();
        Voter v=new Voter();
        v=vot.displayCombo(s);
        jtcnic.setText(Long.toString(v.getVoter_cnic()));
        jtfullname.setText(v.getVoter_fullname());
        jtfathername.setText(v.getVoter_fathername());
        jtphoneno.setText(Long.toString(v.getVoter_phoneno()));
        jtmobileno.setText(Long.toString(v.getVoter_mobileno()));
        jtemail.setText(v.getVoter_email());
        jlrecordno.setText(Integer.toString(v.getVoter_id()));
        imageIcon = new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
        jlpicture.setIcon(imageIcon);
        
    } catch (SQLException ex) {
        Logger.getLogger(VoterForm.class.getName()).log(Level.SEVERE, null, ex);}
        
    }//GEN-LAST:event_jcsearchActionPerformed

    private void jlpictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlpictureMouseClicked
        // TODO add your handling code here:
        if(x=="Update" | x=="Create"){
        javax.swing.JFileChooser fileChooser=new javax.swing.JFileChooser();
        javax.swing.filechooser.FileFilter ff= new javax.swing.filechooser.FileNameExtensionFilter("JPEG and PNG Files","jpg","jpeg","png");
        fileChooser.setFileFilter(ff);
        int returnVal;
        returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            picfile = fileChooser.getSelectedFile();
            //jlpicture.setText("Picture Imported");
            jlpicture.setIcon(new javax.swing.ImageIcon(""+picfile));
           // javax.swing.ImageIcon im=new javax.swing.ImageIcon(v.getVoter_picture().getBytes(1, (int)v.getVoter_picture().length()));
            //jlpicture.setIcon(im);
        } 
        else {
            System.out.println("File access cancelled by user.");}
        }
    }//GEN-LAST:event_jlpictureMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Index().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void jlpictureActionPerformed(java.awt.event.MouseEvent evt){
        javax.swing.JFileChooser jf=new javax.swing.JFileChooser();
       // jf.setSelectedFile(new File());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VoterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VoterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Cancel;
    public javax.swing.JButton Ok;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbcreate;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbnextval;
    private javax.swing.JButton jbpreviousval;
    private javax.swing.JButton jbsearch;
    private javax.swing.JButton jbtakefirst;
    private javax.swing.JButton jbtakelast;
    private javax.swing.JButton jbupdate;
    public static javax.swing.JComboBox jcsearch;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel jlfathername;
    private javax.swing.JLabel jlfullname;
    private javax.swing.JLabel jlmobileno;
    private javax.swing.JLabel jlphoneno;
    public static javax.swing.JLabel jlpicture;
    public javax.swing.JLabel jlrecordno;
    public static javax.swing.JTextField jtcnic;
    public static javax.swing.JTextField jtemail;
    public static javax.swing.JTextField jtfathername;
    public static javax.swing.JTextField jtfullname;
    public static javax.swing.JTextField jtmobileno;
    public static javax.swing.JTextField jtphoneno;
    // End of variables declaration//GEN-END:variables
}
